name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # This enables manual triggering
#  push:
#    branches: [ main ]  # Automatically deploy on pushes to main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup public directory for build
        run: |
          # Create public directory and copy images and CSS to it before build
          echo "Setting up public directory..."
          mkdir -p public
          cp -f *.png public/ 2>/dev/null || true
          cp -f style.css public/ 2>/dev/null || true
      
      - name: Build
        run: npm run build
      
      - name: Copy index file
        run: |
          # Copy index-vite.html as index.html
          cp -f index-vite.html dist/index.html
      
      - name: Ensure assets are properly deployed
        run: |
          # Double-check if CSS exists in dist
          if [ ! -f dist/style.css ]; then
            echo "Style.css not found in dist, copying directly..."
            cp -f style.css dist/
          fi

          # Copy any PNG files not already in dist
          for img in *.png; do
            if [ -f "$img" ] && [ ! -f "dist/$img" ]; then
              echo "Copying $img to dist..."
              cp -f "$img" dist/
            fi
          done

          echo "Contents of dist directory after build and fixes:"
          ls -la dist/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4